// <auto-generated />
using System;
using FinanceAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceAPI.Infrastructure.Migrations
{
    [DbContext(typeof(FinanceManagerDbContext))]
    [Migration("20260922200755_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceAPI.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "CREATE",
                            Code = "USER_CREATE",
                            Module = "USER"
                        },
                        new
                        {
                            Id = 2,
                            Action = "READ",
                            Code = "USER_READ",
                            Module = "USER"
                        },
                        new
                        {
                            Id = 3,
                            Action = "UPDATE",
                            Code = "USER_UPDATE",
                            Module = "USER"
                        },
                        new
                        {
                            Id = 4,
                            Action = "DELETE",
                            Code = "USER_DELETE",
                            Module = "USER"
                        },
                        new
                        {
                            Id = 5,
                            Action = "LIST",
                            Code = "USER_LIST",
                            Module = "USER"
                        },
                        new
                        {
                            Id = 6,
                            Action = "RESET_PASSWORD",
                            Code = "USER_RESET_PASSWORD",
                            Module = "USER"
                        },
                        new
                        {
                            Id = 7,
                            Action = "CHANGE_PASSWORD",
                            Code = "USER_CHANGE_PASSWORD",
                            Module = "USER"
                        },
                        new
                        {
                            Id = 8,
                            Action = "ASSIGN_ROLE",
                            Code = "USER_ASSIGN_ROLE",
                            Module = "USER"
                        },
                        new
                        {
                            Id = 9,
                            Action = "ACTIVATE",
                            Code = "USER_ACTIVATE",
                            Module = "USER"
                        },
                        new
                        {
                            Id = 10,
                            Action = "DEACTIVATE",
                            Code = "USER_DEACTIVATE",
                            Module = "USER"
                        },
                        new
                        {
                            Id = 11,
                            Action = "CREATE",
                            Code = "ROLE_CREATE",
                            Module = "ROLE"
                        },
                        new
                        {
                            Id = 12,
                            Action = "READ",
                            Code = "ROLE_READ",
                            Module = "ROLE"
                        },
                        new
                        {
                            Id = 13,
                            Action = "UPDATE",
                            Code = "ROLE_UPDATE",
                            Module = "ROLE"
                        },
                        new
                        {
                            Id = 14,
                            Action = "DELETE",
                            Code = "ROLE_DELETE",
                            Module = "ROLE"
                        },
                        new
                        {
                            Id = 15,
                            Action = "LIST",
                            Code = "ROLE_LIST",
                            Module = "ROLE"
                        },
                        new
                        {
                            Id = 16,
                            Action = "READ",
                            Code = "PERMISSION_READ",
                            Module = "PERMISSION"
                        },
                        new
                        {
                            Id = 17,
                            Action = "LIST",
                            Code = "PERMISSION_LIST",
                            Module = "PERMISSION"
                        },
                        new
                        {
                            Id = 18,
                            Action = "ASSIGN_TO_ROLE",
                            Code = "PERMISSION_ASSIGN_TO_ROLE",
                            Module = "PERMISSION"
                        },
                        new
                        {
                            Id = 19,
                            Action = "REMOVE_FROM_ROLE",
                            Code = "PERMISSION_REMOVE_FROM_ROLE",
                            Module = "PERMISSION"
                        },
                        new
                        {
                            Id = 20,
                            Action = "VIEW_ROLE_PERMISSIONS",
                            Code = "PERMISSION_VIEW_ROLE_PERMISSIONS",
                            Module = "PERMISSION"
                        },
                        new
                        {
                            Id = 21,
                            Action = "VIEW_USER_PERMISSIONS",
                            Code = "PERMISSION_VIEW_USER_PERMISSIONS",
                            Module = "PERMISSION"
                        },
                        new
                        {
                            Id = 22,
                            Action = "CREATE",
                            Code = "PERMISSION_CREATE",
                            Module = "PERMISSION"
                        },
                        new
                        {
                            Id = 23,
                            Action = "UPDATE",
                            Code = "PERMISSION_UPDATE",
                            Module = "PERMISSION"
                        },
                        new
                        {
                            Id = 24,
                            Action = "DELETE",
                            Code = "PERMISSION_DELETE",
                            Module = "PERMISSION"
                        });
                });

            modelBuilder.Entity("FinanceAPI.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReplacedByToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_ExpiresAt");

                    b.HasIndex("ReplacedByToken")
                        .HasDatabaseName("IX_RefreshTokens_ReplacedByToken");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Token_Unique");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("FinanceAPI.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Name_Unique");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("FinanceAPI.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("Role_Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7
                        });
                });

            modelBuilder.Entity("FinanceAPI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FinanceAPI.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("FinanceAPI.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceAPI.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("FinanceAPI.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Permissions");

                    b.HasOne("FinanceAPI.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Roles");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FinanceAPI.Domain.Entities.User", b =>
                {
                    b.HasOne("FinanceAPI.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FinanceAPI.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("FinanceAPI.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FinanceAPI.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
